name: Build docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      should-deploy:
        description: 'Whether to deploy the built docs (yes) or not (no)'
        required: false
        default: 'yes'
      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.x
      
      - run: pip install -r requirements-dev.txt
      
      - name: Build the docs
        run: mkdocs build
      
      - name: Upload the built site
        uses: actions/upload-artifact@v2.2.2
        with:
          name: docs
          path: site
      
      - name: Deploy
        if: github.event.inputs.should-deploy == 'yes' || github.event_name != 'pull_request'
        run: mkdocs gh-deploy
      
      
        
